// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_student.proto

package src.proto_student;

public final class Student {
  private Student() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StudentSummaryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 ondiskVersion = 1;
    /**
     * <code>required uint32 ondiskVersion = 1;</code>
     */
    boolean hasOndiskVersion();
    /**
     * <code>required uint32 ondiskVersion = 1;</code>
     */
    int getOndiskVersion();

    // optional string codec = 2;
    /**
     * <code>optional string codec = 2;</code>
     */
    boolean hasCodec();
    /**
     * <code>optional string codec = 2;</code>
     */
    java.lang.String getCodec();
    /**
     * <code>optional string codec = 2;</code>
     */
    com.google.protobuf.ByteString
        getCodecBytes();

    // repeated .Section sections = 3;
    /**
     * <code>repeated .Section sections = 3;</code>
     */
    java.util.List<src.proto_student.Student.Section> 
        getSectionsList();
    /**
     * <code>repeated .Section sections = 3;</code>
     */
    src.proto_student.Student.Section getSections(int index);
    /**
     * <code>repeated .Section sections = 3;</code>
     */
    int getSectionsCount();
    /**
     * <code>repeated .Section sections = 3;</code>
     */
    java.util.List<? extends src.proto_student.Student.SectionOrBuilder> 
        getSectionsOrBuilderList();
    /**
     * <code>repeated .Section sections = 3;</code>
     */
    src.proto_student.Student.SectionOrBuilder getSectionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code StudentSummary}
   */
  public static final class StudentSummary extends
      com.google.protobuf.GeneratedMessage
      implements StudentSummaryOrBuilder {
    // Use StudentSummary.newBuilder() to construct.
    private StudentSummary(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StudentSummary(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StudentSummary defaultInstance;
    public static StudentSummary getDefaultInstance() {
      return defaultInstance;
    }

    public StudentSummary getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StudentSummary(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ondiskVersion_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              codec_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                sections_ = new java.util.ArrayList<src.proto_student.Student.Section>();
                mutable_bitField0_ |= 0x00000004;
              }
              sections_.add(input.readMessage(src.proto_student.Student.Section.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          sections_ = java.util.Collections.unmodifiableList(sections_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return src.proto_student.Student.internal_static_StudentSummary_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return src.proto_student.Student.internal_static_StudentSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              src.proto_student.Student.StudentSummary.class, src.proto_student.Student.StudentSummary.Builder.class);
    }

    public static com.google.protobuf.Parser<StudentSummary> PARSER =
        new com.google.protobuf.AbstractParser<StudentSummary>() {
      public StudentSummary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StudentSummary(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StudentSummary> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 ondiskVersion = 1;
    public static final int ONDISKVERSION_FIELD_NUMBER = 1;
    private int ondiskVersion_;
    /**
     * <code>required uint32 ondiskVersion = 1;</code>
     */
    public boolean hasOndiskVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 ondiskVersion = 1;</code>
     */
    public int getOndiskVersion() {
      return ondiskVersion_;
    }

    // optional string codec = 2;
    public static final int CODEC_FIELD_NUMBER = 2;
    private java.lang.Object codec_;
    /**
     * <code>optional string codec = 2;</code>
     */
    public boolean hasCodec() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string codec = 2;</code>
     */
    public java.lang.String getCodec() {
      java.lang.Object ref = codec_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          codec_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string codec = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodecBytes() {
      java.lang.Object ref = codec_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        codec_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .Section sections = 3;
    public static final int SECTIONS_FIELD_NUMBER = 3;
    private java.util.List<src.proto_student.Student.Section> sections_;
    /**
     * <code>repeated .Section sections = 3;</code>
     */
    public java.util.List<src.proto_student.Student.Section> getSectionsList() {
      return sections_;
    }
    /**
     * <code>repeated .Section sections = 3;</code>
     */
    public java.util.List<? extends src.proto_student.Student.SectionOrBuilder> 
        getSectionsOrBuilderList() {
      return sections_;
    }
    /**
     * <code>repeated .Section sections = 3;</code>
     */
    public int getSectionsCount() {
      return sections_.size();
    }
    /**
     * <code>repeated .Section sections = 3;</code>
     */
    public src.proto_student.Student.Section getSections(int index) {
      return sections_.get(index);
    }
    /**
     * <code>repeated .Section sections = 3;</code>
     */
    public src.proto_student.Student.SectionOrBuilder getSectionsOrBuilder(
        int index) {
      return sections_.get(index);
    }

    private void initFields() {
      ondiskVersion_ = 0;
      codec_ = "";
      sections_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOndiskVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, ondiskVersion_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCodecBytes());
      }
      for (int i = 0; i < sections_.size(); i++) {
        output.writeMessage(3, sections_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, ondiskVersion_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCodecBytes());
      }
      for (int i = 0; i < sections_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, sections_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static src.proto_student.Student.StudentSummary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.proto_student.Student.StudentSummary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.proto_student.Student.StudentSummary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.proto_student.Student.StudentSummary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.proto_student.Student.StudentSummary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static src.proto_student.Student.StudentSummary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static src.proto_student.Student.StudentSummary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static src.proto_student.Student.StudentSummary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static src.proto_student.Student.StudentSummary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static src.proto_student.Student.StudentSummary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(src.proto_student.Student.StudentSummary prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StudentSummary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements src.proto_student.Student.StudentSummaryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return src.proto_student.Student.internal_static_StudentSummary_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return src.proto_student.Student.internal_static_StudentSummary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                src.proto_student.Student.StudentSummary.class, src.proto_student.Student.StudentSummary.Builder.class);
      }

      // Construct using src.proto_student.Student.StudentSummary.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSectionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ondiskVersion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        codec_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (sectionsBuilder_ == null) {
          sections_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          sectionsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return src.proto_student.Student.internal_static_StudentSummary_descriptor;
      }

      public src.proto_student.Student.StudentSummary getDefaultInstanceForType() {
        return src.proto_student.Student.StudentSummary.getDefaultInstance();
      }

      public src.proto_student.Student.StudentSummary build() {
        src.proto_student.Student.StudentSummary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public src.proto_student.Student.StudentSummary buildPartial() {
        src.proto_student.Student.StudentSummary result = new src.proto_student.Student.StudentSummary(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ondiskVersion_ = ondiskVersion_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.codec_ = codec_;
        if (sectionsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            sections_ = java.util.Collections.unmodifiableList(sections_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.sections_ = sections_;
        } else {
          result.sections_ = sectionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof src.proto_student.Student.StudentSummary) {
          return mergeFrom((src.proto_student.Student.StudentSummary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(src.proto_student.Student.StudentSummary other) {
        if (other == src.proto_student.Student.StudentSummary.getDefaultInstance()) return this;
        if (other.hasOndiskVersion()) {
          setOndiskVersion(other.getOndiskVersion());
        }
        if (other.hasCodec()) {
          bitField0_ |= 0x00000002;
          codec_ = other.codec_;
          onChanged();
        }
        if (sectionsBuilder_ == null) {
          if (!other.sections_.isEmpty()) {
            if (sections_.isEmpty()) {
              sections_ = other.sections_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSectionsIsMutable();
              sections_.addAll(other.sections_);
            }
            onChanged();
          }
        } else {
          if (!other.sections_.isEmpty()) {
            if (sectionsBuilder_.isEmpty()) {
              sectionsBuilder_.dispose();
              sectionsBuilder_ = null;
              sections_ = other.sections_;
              bitField0_ = (bitField0_ & ~0x00000004);
              sectionsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSectionsFieldBuilder() : null;
            } else {
              sectionsBuilder_.addAllMessages(other.sections_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOndiskVersion()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        src.proto_student.Student.StudentSummary parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (src.proto_student.Student.StudentSummary) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 ondiskVersion = 1;
      private int ondiskVersion_ ;
      /**
       * <code>required uint32 ondiskVersion = 1;</code>
       */
      public boolean hasOndiskVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 ondiskVersion = 1;</code>
       */
      public int getOndiskVersion() {
        return ondiskVersion_;
      }
      /**
       * <code>required uint32 ondiskVersion = 1;</code>
       */
      public Builder setOndiskVersion(int value) {
        bitField0_ |= 0x00000001;
        ondiskVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 ondiskVersion = 1;</code>
       */
      public Builder clearOndiskVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ondiskVersion_ = 0;
        onChanged();
        return this;
      }

      // optional string codec = 2;
      private java.lang.Object codec_ = "";
      /**
       * <code>optional string codec = 2;</code>
       */
      public boolean hasCodec() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string codec = 2;</code>
       */
      public java.lang.String getCodec() {
        java.lang.Object ref = codec_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          codec_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string codec = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCodecBytes() {
        java.lang.Object ref = codec_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          codec_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string codec = 2;</code>
       */
      public Builder setCodec(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        codec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string codec = 2;</code>
       */
      public Builder clearCodec() {
        bitField0_ = (bitField0_ & ~0x00000002);
        codec_ = getDefaultInstance().getCodec();
        onChanged();
        return this;
      }
      /**
       * <code>optional string codec = 2;</code>
       */
      public Builder setCodecBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        codec_ = value;
        onChanged();
        return this;
      }

      // repeated .Section sections = 3;
      private java.util.List<src.proto_student.Student.Section> sections_ =
        java.util.Collections.emptyList();
      private void ensureSectionsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          sections_ = new java.util.ArrayList<src.proto_student.Student.Section>(sections_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          src.proto_student.Student.Section, src.proto_student.Student.Section.Builder, src.proto_student.Student.SectionOrBuilder> sectionsBuilder_;

      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public java.util.List<src.proto_student.Student.Section> getSectionsList() {
        if (sectionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sections_);
        } else {
          return sectionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public int getSectionsCount() {
        if (sectionsBuilder_ == null) {
          return sections_.size();
        } else {
          return sectionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public src.proto_student.Student.Section getSections(int index) {
        if (sectionsBuilder_ == null) {
          return sections_.get(index);
        } else {
          return sectionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public Builder setSections(
          int index, src.proto_student.Student.Section value) {
        if (sectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSectionsIsMutable();
          sections_.set(index, value);
          onChanged();
        } else {
          sectionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public Builder setSections(
          int index, src.proto_student.Student.Section.Builder builderForValue) {
        if (sectionsBuilder_ == null) {
          ensureSectionsIsMutable();
          sections_.set(index, builderForValue.build());
          onChanged();
        } else {
          sectionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public Builder addSections(src.proto_student.Student.Section value) {
        if (sectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSectionsIsMutable();
          sections_.add(value);
          onChanged();
        } else {
          sectionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public Builder addSections(
          int index, src.proto_student.Student.Section value) {
        if (sectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSectionsIsMutable();
          sections_.add(index, value);
          onChanged();
        } else {
          sectionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public Builder addSections(
          src.proto_student.Student.Section.Builder builderForValue) {
        if (sectionsBuilder_ == null) {
          ensureSectionsIsMutable();
          sections_.add(builderForValue.build());
          onChanged();
        } else {
          sectionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public Builder addSections(
          int index, src.proto_student.Student.Section.Builder builderForValue) {
        if (sectionsBuilder_ == null) {
          ensureSectionsIsMutable();
          sections_.add(index, builderForValue.build());
          onChanged();
        } else {
          sectionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public Builder addAllSections(
          java.lang.Iterable<? extends src.proto_student.Student.Section> values) {
        if (sectionsBuilder_ == null) {
          ensureSectionsIsMutable();
          super.addAll(values, sections_);
          onChanged();
        } else {
          sectionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public Builder clearSections() {
        if (sectionsBuilder_ == null) {
          sections_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          sectionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public Builder removeSections(int index) {
        if (sectionsBuilder_ == null) {
          ensureSectionsIsMutable();
          sections_.remove(index);
          onChanged();
        } else {
          sectionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public src.proto_student.Student.Section.Builder getSectionsBuilder(
          int index) {
        return getSectionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public src.proto_student.Student.SectionOrBuilder getSectionsOrBuilder(
          int index) {
        if (sectionsBuilder_ == null) {
          return sections_.get(index);  } else {
          return sectionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public java.util.List<? extends src.proto_student.Student.SectionOrBuilder> 
           getSectionsOrBuilderList() {
        if (sectionsBuilder_ != null) {
          return sectionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sections_);
        }
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public src.proto_student.Student.Section.Builder addSectionsBuilder() {
        return getSectionsFieldBuilder().addBuilder(
            src.proto_student.Student.Section.getDefaultInstance());
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public src.proto_student.Student.Section.Builder addSectionsBuilder(
          int index) {
        return getSectionsFieldBuilder().addBuilder(
            index, src.proto_student.Student.Section.getDefaultInstance());
      }
      /**
       * <code>repeated .Section sections = 3;</code>
       */
      public java.util.List<src.proto_student.Student.Section.Builder> 
           getSectionsBuilderList() {
        return getSectionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          src.proto_student.Student.Section, src.proto_student.Student.Section.Builder, src.proto_student.Student.SectionOrBuilder> 
          getSectionsFieldBuilder() {
        if (sectionsBuilder_ == null) {
          sectionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              src.proto_student.Student.Section, src.proto_student.Student.Section.Builder, src.proto_student.Student.SectionOrBuilder>(
                  sections_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          sections_ = null;
        }
        return sectionsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:StudentSummary)
    }

    static {
      defaultInstance = new StudentSummary(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:StudentSummary)
  }

  public interface SectionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string name = 1;
    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional uint64 length = 2;
    /**
     * <code>optional uint64 length = 2;</code>
     */
    boolean hasLength();
    /**
     * <code>optional uint64 length = 2;</code>
     */
    long getLength();
  }
  /**
   * Protobuf type {@code Section}
   */
  public static final class Section extends
      com.google.protobuf.GeneratedMessage
      implements SectionOrBuilder {
    // Use Section.newBuilder() to construct.
    private Section(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Section(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Section defaultInstance;
    public static Section getDefaultInstance() {
      return defaultInstance;
    }

    public Section getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Section(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              length_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return src.proto_student.Student.internal_static_Section_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return src.proto_student.Student.internal_static_Section_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              src.proto_student.Student.Section.class, src.proto_student.Student.Section.Builder.class);
    }

    public static com.google.protobuf.Parser<Section> PARSER =
        new com.google.protobuf.AbstractParser<Section>() {
      public Section parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Section(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Section> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint64 length = 2;
    public static final int LENGTH_FIELD_NUMBER = 2;
    private long length_;
    /**
     * <code>optional uint64 length = 2;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 length = 2;</code>
     */
    public long getLength() {
      return length_;
    }

    private void initFields() {
      name_ = "";
      length_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, length_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, length_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static src.proto_student.Student.Section parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.proto_student.Student.Section parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.proto_student.Student.Section parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.proto_student.Student.Section parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.proto_student.Student.Section parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static src.proto_student.Student.Section parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static src.proto_student.Student.Section parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static src.proto_student.Student.Section parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static src.proto_student.Student.Section parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static src.proto_student.Student.Section parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(src.proto_student.Student.Section prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Section}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements src.proto_student.Student.SectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return src.proto_student.Student.internal_static_Section_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return src.proto_student.Student.internal_static_Section_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                src.proto_student.Student.Section.class, src.proto_student.Student.Section.Builder.class);
      }

      // Construct using src.proto_student.Student.Section.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        length_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return src.proto_student.Student.internal_static_Section_descriptor;
      }

      public src.proto_student.Student.Section getDefaultInstanceForType() {
        return src.proto_student.Student.Section.getDefaultInstance();
      }

      public src.proto_student.Student.Section build() {
        src.proto_student.Student.Section result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public src.proto_student.Student.Section buildPartial() {
        src.proto_student.Student.Section result = new src.proto_student.Student.Section(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.length_ = length_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof src.proto_student.Student.Section) {
          return mergeFrom((src.proto_student.Student.Section)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(src.proto_student.Student.Section other) {
        if (other == src.proto_student.Student.Section.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        src.proto_student.Student.Section parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (src.proto_student.Student.Section) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional uint64 length = 2;
      private long length_ ;
      /**
       * <code>optional uint64 length = 2;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 length = 2;</code>
       */
      public long getLength() {
        return length_;
      }
      /**
       * <code>optional uint64 length = 2;</code>
       */
      public Builder setLength(long value) {
        bitField0_ |= 0x00000002;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 length = 2;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Section)
    }

    static {
      defaultInstance = new Section(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Section)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StudentSummary_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StudentSummary_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Section_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Section_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto_student.proto\"R\n\016StudentSummary\022" +
      "\025\n\rondiskVersion\030\001 \002(\r\022\r\n\005codec\030\002 \001(\t\022\032\n" +
      "\010sections\030\003 \003(\0132\010.Section\"\'\n\007Section\022\014\n\004" +
      "name\030\001 \001(\t\022\016\n\006length\030\002 \001(\004B\034\n\021src.proto_" +
      "studentB\007Student"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_StudentSummary_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_StudentSummary_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_StudentSummary_descriptor,
              new java.lang.String[] { "OndiskVersion", "Codec", "Sections", });
          internal_static_Section_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Section_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Section_descriptor,
              new java.lang.String[] { "Name", "Length", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
